### ISSUE TITLE
RxSwift support

### ISSUE THREAD

**Issue by dsrees** [davidstump/SwiftPhoenixClient#138]
Provide an Rx extension to the client

Progress Checklist

- [x]  Restructure project to have single targets that support multiple platforms (#147)
- [x] Add RxSwift as a second target that depends upon the main SwiftPhoenix target (#147)
- [x] Add client code and tests back into the project under the SwiftPhoenix target (#148)
- [x] Add initial Rx extension to `channel.on` function (#149)
- [x] Ensure fastlane and travis ci builds are running under new project structure
- [ ] Ensure docs are still set up correctly
- [ ] Add RxSwift documentation
- [ ] Setup cocoapods to deploy SwiftPhoenix and RxSwiftPhoenix
- [ ] Release notes for breaking changes
- [x] Example projects
- [ ] use SwiftPackageManager instead of Carthage

**Comment by dsrees** [comment]
Active work for this is available in the `rxswift` branch. Issue will be closed when merged to master

**Comment by sjmueller** [comment]
Is Apple's `Combine.framework` being considered rather than rxswift?

**Comment by dsrees** [comment]
It is not, seeing that it limits the target to iOS 13, removing support for older versions of iOS. Ideally I would like to make the lib behave similar to `Moya` which has multiple targets supporting `Reactive`, `Rx`, `Combine`, etc. I haven't had time to work on this however so its not currently a high priority for me.

**Comment by dchohfi** [comment]
Is this planed to be released? Need help to finish implementation?

**Comment by dsrees** [comment]
v2.0.0 was released which includes support for RxSwift. Currently, only the `channel.on(event)` has been made reactive. If there are other features/functions you think would benefit from RxSwift, please open a new issue
